### ISSUE TITLE
Data loss when uploading tons of metrics

### ISSUE THREAD

**Issue by dimaqq** [orionvm/potsdb#2]
I have OpenTSDB configured to create metrics in demand, and my code is basically this:

```py
cl = potsb.Client(someipaddress)
for filename in glob.glob(...):
    for datum, count in json.load(open(filename)).items():
        cl.send(datum, count, timestamp=xxxx, foo=yyyyy)
cl.wait()
```

Which would insert some 1700 unique metrics and some 74K data points total.

However, a single run only inserts some 30 or so metrics, and running same script on same data again will add another 5 or 10 metrics, etc.

As a work-around, I changed my code to open and wait on new connection per file, now I get more data in, but still not all.

**Comment by mcclymont** [comment]
Thanks for letting us know about this issue.

I have found that the data loss is due to the default values we have for qsize in combination with the default Metrics Per Second limit. Once the internal Queue is full, it drops metrics. We coded it this way because we didn't want python to keep allocating memory forever if OpenTSDB dies and it can't send the data over TCP for an extended time. The defaults didn't work well for you because you're doing a data-loading scenario, rather than our imagined "a few data points here and there in a long running process"

I have updated the library with higher defaults for qsize and mps. Mps is now unlimited, and qsize deafult is 100k.

Can you try updating the python package, then try running your script again using qsize=0 (unlimited)
i.e.
```
cl = potsdb.Client(someipaddress, qsize=0)
```

**Comment by dimaqq** [comment]
I moved on to another prototype, I won't be able to retest this for a while.
Thanks for fixing it though!
